config:
  namespace: eyetap
  clusterName: cluster
  db: 
    username: eyetap
    db: eyetap
    password: eyetap

app:
  image:
    repository: postgres
    tag: 18
    pullPolicy: Always

  restartPolicy: OnFailure
  port: 5432
  name: eyetap-postgres
  # pvcs:
  #   - accessMode: ReadWriteOnce
  #     name: default
  #     storage: 1Gi
  #     storageClassName: null
  #     existingClaim: false
